import type { Metadata, Viewport } from 'next';
import { Suspense } from 'react';
import { Geist, Geist_Mono } from 'next/font/google';
import { AnalyticsProvider } from '@/components/analytics/AnalyticsProvider';
import { Navigation, BackgroundImage } from '@/components/layout';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

/** Default Safari / mobile browser UI tint; case-studies layout overrides to white. */
export const viewport: Viewport = {
  themeColor: '#0a0a0a',
};

/** Empty string is a common .env mistake and breaks `new URL('')` → 500 on every route. */
function resolveSiteUrl(): string {
  const fromEnv = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (fromEnv) {
    try {
      // Validate; invalid values would throw at metadataBase
      new URL(fromEnv);
      return fromEnv.replace(/\/$/, '');
    } catch {
      /* fall through */
    }
  }
  if (process.env.VERCEL_URL) return `https://${process.env.VERCEL_URL}`.replace(/\/$/, '');
  return 'http://localhost:3000';
}

const siteUrl = resolveSiteUrl();

/** Static JPEG in /public — generated by scripts/generate-og.mjs (home hero preview). */
const ogImage = {
  url: '/og-share.jpg',
  width: 1200,
  height: 630,
  alt: "Bryce's Portfolio — home hero (butterflies and headline)",
  type: 'image/jpeg',
} as const;

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Bryce's Portfolio",
  description:
    'A product designer who loves turning ideas into reality. Chat with BAR 9000 to learn more about my work.',
  openGraph: {
    title: "Bryce's Portfolio",
    description: 'A product designer who loves turning ideas into reality.',
    type: 'website',
    siteName: "Bryce's Portfolio",
    images: [ogImage],
  },
  twitter: {
    card: 'summary_large_image',
    title: "Bryce's Portfolio",
    description: 'A product designer who loves turning ideas into reality.',
    images: [ogImage.url],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundImage />
        <Navigation />
        <Suspense fallback={null}>
          <AnalyticsProvider />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
